# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: ArtifactoryNpm@2
  inputs:
    command: 'install'
    artifactoryService: 'Artifactory'
    sourceRepo: 'situsamc-npm-virtual'
    collectBuildInfo: true
    threads: '10'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    projectKey: situsAMC

- script: |
    npm run build
  displayName: 'Build'

- script: |
    npm pack
  displayName: 'Build the package'
- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'Artifactory'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
              "files": [
                {
                  "pattern": "npm-example*",
                  "target": "situsamc-npm-dev-local/"
                }
              ]
      }
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    failNoOp: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'Artifactory'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: JFrogBuildScan@1
  inputs:
    allowFailBuild: false
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: situsAMC
    xrayConnection: 'soleng-xray2'
    vuln: true
- task: JFrogBuildPromotion@1
  inputs:
    artifactoryConnection: 'JFrog Artifactory V2'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    targetRepo: 'situsamc-npm-qa-local'
    status: 'Released'
    comment: 'ReadyForQA'
    sourceRepo: 'situsamc-npm-dev-local'
    includeDependencies: true
    copy: true
    dryRun: false