# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: ArtifactoryNpm@2
  inputs:
    command: 'install'
    artifactoryService: 'Artifactory'
    sourceRepo: 'alpha-npm-virtual'
    collectBuildInfo: true
    threads: '10'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true

- script: |
    npm run build
  displayName: 'Build'

- script: |
    npm pack
  displayName: 'Build the package'

- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'Artifactory'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
              "files": [
                {
                  "pattern": "npm-example*",
                  "target": "alpha-npm-dev-local/"
                }
              ]
      }
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    failNoOp: true

- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'Artifactory'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'soleng-xray2'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: false

- task: ArtifactoryBuildPromotion@1
  inputs:
    artifactoryService: 'Artifactory'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    targetRepo: 'alpha-npm-prod-local'
    status: 'Released'
    comment: 'ReadyForProd'
    sourceRepo: 'alpha-npm-dev-local'
    includeDependencies: true
    copy: true
    dryRun: false
- task: JFrogAudit@1
  inputs:
    xrayConnection: 'soleng-xray2'
    watchesSource: 'project'
    project: 'alpha'
    allowFailBuild: true
